server:
   port: 7777
  
spring:
  application:
    name: configuration-server
    
  cloud:
      config:
        server:
          git:
            uri: https://github.com/shivamsoni4475/olx-config.git
            default-label: main
            username: shivamsoni4475
            password: Soni@3371
            clone-on-start: true