server:
  port: 9002
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
      name: advertise-service
  zipkin:
    base-url: http://localhost:9411      
  config:
     import: configserver:http://localhost:7777
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /olx-advertises  
  health:    
    circuitbreakers:      
      enabled: true
  endpoint:    
    health:      
      show-details: always
      
resilience4j:
  circuitbreaker:
    instances:
      STATUS-FROM-MASTER-DATA-SERVICE:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s